spring:
  application:
    name: pathprep-backend
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/pathprep-ai}
      database: ${MONGODB_DATABASE:pathprep-ai}
  mvc:
    cors:
      mappings:
        "/**":
          allowed-origins: "*"
          allowed-methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
          allowed-headers: "*"
          max-age: 3600
  profiles:
    include: secrets

server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /api

# SpringDoc OpenAPI Configuration
springdoc:
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

groq:
  api-key: ${GROQ_API_KEY:your-api-key-here}
  base-url: ${GROQ_BASE_URL:https://api.groq.com/openai/v1}
  timeout: 30s
  max-retries: 3
  models:
    default: llama3-8b-8192
    fast: llama3-8b-8192
    smart: llama3-70b-8192
    code: codellama-34b-instruct

groq-rate-limit:
  requests-per-minute: 30
  requests-per-day: 14400

# Application settings
pathprep:
  show-actuator: true
  paths-to-match: /api/**
  packages-to-scan: com.pathprep.controller

# Logging configuration
logging:
  level:
    com.pathprep: INFO
    org.springframework.web: INFO
    org.springdoc: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  health:
    mongo:
      enabled: true
