spring:
  application:
    name: pathprep-backend
  data:
    mongodb:
      uri: mongodb+srv://prasadsawantpvt:G5XI2e2cZkb0w59f@careerpilotcluster.q2fzpik.mongodb.net/pathprep-ai?retryWrites=true&w=majority
      database: pathprep-ai
      auto-index-creation: true
      ssl:
        enabled: true
      connection-timeout-ms: 30000
      socket-timeout-ms: 60000
      min-connections: 5
      max-connections: 100
  mvc:
    cors:
      mappings:
        "/**":
          allowed-origins: "*"
          allowed-methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
          allowed-headers: "*"
          max-age: 3600
  profiles:
    include: secrets

server:
  port: 8080
  servlet:
    context-path: /api

# SpringDoc OpenAPI Configuration
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    doc-expansion: none
    use-root-path: true
    disable-swagger-default-url: true
    urls:
      - url: /v3/api-docs
        name: API V1
  api-docs:
    path: /v3/api-docs
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  show-actuator: false
  cache:
    disabled: true

groq:
  base-url: ${GROQ_BASE_URL:https://api.groq.com/openai/v1}
  timeout: 30s
  max-retries: 3
  models:
    default: llama3-8b-8192
    fast: llama3-8b-8192
    smart: llama3-70b-8192
    code: codellama-34b-instruct

groq-rate-limit:
  requests-per-minute: 30
  requests-per-day: 14400

# Application settings
pathprep:
  show-actuator: true
  paths-to-match: /api/**
  packages-to-scan: com.pathprep.controller

# Logging configuration
logging:
  level:
    com.pathprep: INFO
    org.springframework.web: INFO
    org.springdoc: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Actuator configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  health:
    mongo:
      enabled: true


  logging:
    level:
      org:
        springframework:
          web:
            filter:
              CommonsRequestLoggingFilter: DEBUG
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
